import { insertRows } from "./sql.js";
import type { SeedData } from "./types.js";

const seedTimestamp = "2026-01-01T00:00:00.000Z";

export const renderSeedSql = (data: SeedData): string => {
  const statements = [
    "-- Generated by db/seed/generate.ts. Do not edit by hand.",
    "BEGIN;",
    insertRows(
      "catalog.categories",
      ["id", "name", "parent_id"],
      data.categories.map((row) => ({
        id: row.id,
        name: row.name,
        parent_id: row.parentId
      })),
      "(id)"
    ),
    insertRows(
      "catalog.products",
      [
        "id",
        "sku",
        "name",
        "description",
        "category_id",
        "base_price_cents",
        "currency",
        "status",
        "created_at",
        "updated_at"
      ],
      data.products.map((row) => ({
        id: row.id,
        sku: row.sku,
        name: row.name,
        description: row.description,
        category_id: row.categoryId,
        base_price_cents: row.basePriceCents,
        currency: row.currency,
        status: row.status,
        created_at: seedTimestamp,
        updated_at: seedTimestamp
      })),
      "(id)"
    ),
    insertRows(
      "inventory.warehouses",
      ["id", "code", "name", "region"],
      data.warehouses.map((row) => ({
        id: row.id,
        code: row.code,
        name: row.name,
        region: row.region
      })),
      "(id)"
    ),
    insertRows(
      "inventory.stock_levels",
      ["warehouse_id", "product_id", "on_hand", "reserved", "updated_at"],
      data.stockLevels.map((row) => ({
        warehouse_id: row.warehouseId,
        product_id: row.productId,
        on_hand: row.onHand,
        reserved: 0,
        updated_at: seedTimestamp
      })),
      "(warehouse_id, product_id)"
    ),
    insertRows(
      "orders.customers",
      ["id", "code", "name", "tier", "country", "currency"],
      data.customers.map((row) => ({
        id: row.id,
        code: row.code,
        name: row.name,
        tier: row.tier,
        country: row.country,
        currency: row.currency
      })),
      "(id)"
    ),
    insertRows(
      "payments.fx_rates",
      ["base", "quote", "rate", "fetched_at"],
      data.fxRates.map((row) => ({
        base: row.base,
        quote: row.quote,
        rate: row.rate,
        fetched_at: seedTimestamp
      })),
      "(base, quote)"
    ),
    insertRows(
      "catalog.price_rules",
      ["id", "product_id", "rule_type", "value", "priority", "starts_at", "ends_at", "created_at"],
      data.priceRules.map((row) => ({
        id: row.id,
        product_id: row.productId,
        rule_type: row.ruleType,
        value: row.value,
        priority: row.priority,
        starts_at: "2025-01-01T00:00:00.000Z",
        ends_at: "2027-01-01T00:00:00.000Z",
        created_at: seedTimestamp
      })),
      "(id)"
    ),
    "COMMIT;"
  ].filter(Boolean);

  return `${statements.join("\n\n")}\n`;
};
